//
//  AppDelegate.swift
//  RecipeApp
//
//  Created by moh on 22/12/2022.
//

import UIKit

@main
class AppDelegate: UIResponder, UIApplicationDelegate {


    func makeCategoryContent(_ categoryId:String,_ recipes:[Recipe]){
        let documentDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        let archiveURL = documentDirectory.appendingPathComponent("Recipe_"+categoryId).appendingPathExtension("plist")
        for recipe in recipes {
            saveImage(image: UIImage(named: recipe.image)!, name: recipe.image)
        }
        
        let propertyListEncoder = PropertyListEncoder()
        let encodedData = try? propertyListEncoder.encode(recipes)
        try? encodedData?.write(to: archiveURL, options: .noFileProtection)
    }
    func saveImage(image: UIImage, name:String) {
        guard let data = image.jpegData(compressionQuality: 1) ?? image.pngData() else {
            return
        }
        guard let directory = try? FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false) as NSURL else {
            return
        }
        do {
            try data.write(to: directory.appendingPathComponent(name)!)
            return
        } catch {
            print(error.localizedDescription)
            return
        }
    }
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        func giveId() -> String {
            return String(UUID().uuidString.split(separator: "-")[0])
        }
        //UserDefaults.standard.set(false, forKey: "signedUp")
        if !signedUp(){
            let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
            var archiveURL = documentsDirectory.appendingPathComponent("categories").appendingPathExtension("plist")
            let propertyListEncoder = PropertyListEncoder()

            let categoryArr: [Category] = [Category(categoryId: giveId(), categoryName: "Mexican"),Category(categoryId: giveId(), categoryName: "American"),Category(categoryId: giveId(), categoryName: "Chinese"),Category(categoryId: giveId(), categoryName: "French")]
            for cat in categoryArr{
                if(cat.categoryName == "Mexican"){
                    makeCategoryContent(cat.categoryId, [
                        Recipe(recipeId:giveId(),image:"VegetarianEnchiladaCasserole.png", recipeName:"Vegetarian Enchilada Casserole", category:cat.categoryId, servingSize:"1 1/2 cups", calories:357, protein:13, carb:42,fat:16,ingredients:"2 tablespoons extra-virgin olive oil\n1 cup chopped onion\n¾ cup chopped poblano peppers\n6 cloves garlic, minced\n1 medium yellow squash, halved and sliced (1/4-inch)\n1 medium zucchini, halved and sliced (1/4-inch)\n1 cup fresh corn kernels (from 2 ears)\n1 cup pico de gallo\n½ teaspoon salt\n1 (15 ounce) can no-salt-added pinto beans, rinsed\n1 (15 ounce) can no-salt-added black beans, rinsed\n8 (6 inch) corn tortillas\n1 ½ cups shredded pepper Jack cheese\n1 avocado, diced\n½ cup scallions\n½ cup reduced-fat sour cream",instructions:"Preheat oven to 350 degrees F. Heat oil in a large skillet over medium-high heat. Add onion, poblanos and garlic; cook, stirring occasionally, until softened, 4 to 5 minutes. Add squash, zucchini, corn, pico de gallo and salt; cook, stirring occasionally, until the liquid comes to a simmer, 5 to 6 minutes. Simmer, stirring occasionally, until the liquid reduces by half, about 2 minutes. Remove from heat; stir in pinto beans and black beans. Coat a 9-by-13-inch baking dish with cooking spray. Spoon one-third of the vegetable mixture into the prepared dish. Top evenly with 4 tortillas. Repeat with half the remaining vegetable mixture and the remaining 4 tortillas. Top with the remaining vegetable mixture. Sprinkle evenly with cheese. Bake until the cheese is bubbly, 25 to 30 minutes. Sprinkle evenly with avocado and scallions. Dollop with sour cream."),
                        Recipe(recipeId:giveId(),image:"Sheet-PanChickenFajitas.png", recipeName:"Sheet-Pan Chicken Fajitas", category:cat.categoryId, servingSize:"2 fajitas per person", calories:357, protein:30, carb:32,fat:12,ingredients:"1 pound boneless, skinless chicken breasts\n2 tablespoons extra-virgin olive oil\n1 tablespoon chili powder\n2 teaspoons ground cumin\n1 teaspoon garlic powder\n¾ teaspoon salt\n1 large red bell pepper, sliced\n1 large yellow bell pepper, sliced\n2 cups sliced red or yellow onion (about 1 large)\n1 tablespoon lime juice\n8 corn tortillas, warmed\nLime wedges, cilantro, sour cream, avocado and/or pico de gallo for serving",instructions:"Preheat oven to 400 degrees F. Coat a large rimmed baking sheet with cooking spray. Cut chicken breasts in half horizontally, then slice crosswise into strips. Combine oil, chili powder, cumin, garlic powder and salt in a large bowl. Add the chicken and stir to coat with the spice mixture. Add bell peppers and onion and stir to combine. Transfer the chicken and vegetables to the prepared baking sheet and spread in an even layer. Roast on the middle rack for 15 minutes. Leave the pan there and turn the broiler to high. Broil until the chicken is cooked through and the vegetables are browning in spots, about 5 minutes more. Remove from oven. Stir in lime juice. Serve the chicken and vegetables in warmed tortillas accompanied by lime wedges and topped with cilantro, sour cream, avocado and/or pico de gallo, if desired."),
                        Recipe(recipeId:giveId(),image:"AdoboChicken&KaleEnchiladas.png", recipeName:"Adobo Chicken & Kale Enchiladas", category:cat.categoryId, servingSize:"1 1/4 cups", calories:415, protein:31, carb:34,fat:17,ingredients:"1 tablespoon extra-virgin olive oil\n8 cups chopped kale\n¼ cup water\n2 cups shredded or diced cooked chicken\n1 teaspoon ground cumin\n¼ teaspoon salt\n¼ teaspoon ground pepper\n1 (10 ounce) can red enchilada sauce (1 1/4 cups)\n¼ cup sour cream\n2-3 tablespoons minced chipotles in adobo\n12 corn tortillas\n¾ cup diced white onion, divided\n1 ½ cups shredded Mexican blend cheese, divided",instructions:"Preheat oven to 450 degrees F. Heat oil in a large cast-iron skillet (12-inch) over medium-high heat. Add kale and water; cook, stirring, until bright green and wilted, about 2 minutes. Stir in chicken, cumin, salt and pepper; cook for 1 minute more. Transfer to a large bowl. Combine enchilada sauce, sour cream and chipotles to taste in a small bowl. Spread 1/2 cup of the mixture in the pan. Place 4 tortillas over the sauce, overlapping them to cover the bottom. Top with half the chicken mixture, 1/4 cup onion and 1/2 cup cheese. Layer on half the remaining sauce, 4 tortillas, the remaining chicken, 1/4 cup onion and 1/2 cup cheese. Top with the remaining tortillas, sauce and cheese. Bake the enchiladas until bubbling, 12 to 15 minutes. Sprinkle with the remaining 1/4 cup onion before serving."),
                        Recipe(recipeId:giveId(),image:"BlackBean-QuinoaBowl.png", recipeName:"Black Bean-Quinoa Bowl", category:cat.categoryId, servingSize:"about 2 cups", calories:500, protein:20, carb:73,fat:16,ingredients:"¾ cup canned black beans, rinsed\n⅔ cup cooked quinoa\n¼ cup hummus\n1 tablespoon lime juice\n¼ medium avocado, diced\n3 tablespoons pico de gallo\n2 tablespoons chopped fresh cilantro",instructions:"Combine beans and quinoa in a bowl. Stir hummus and lime juice together in a small bowl; thin with water to desired consistency. Drizzle the hummus dressing over the beans and quinoa. Top with avocado, pico de gallo and cilantro."),
                        Recipe(recipeId:giveId(),image:"ChickenEnchiladaSoup.png", recipeName:"Chicken Enchilada Soup", category:cat.categoryId, servingSize:"1 1/2 cups", calories:329, protein:26, carb:23,fat:15,ingredients:"1 tablespoon canola oil\n1 cup chopped onion\n3 cloves garlic, minced\n5 cups low-sodium chicken broth\n1 (15 ounce) can diced tomatoes\n1 (4 ounce) can diced green chiles\n6 corn tortillas, chopped\n2 teaspoons chili powder\n1 teaspoon ground cumin\n2 cups shredded cooked chicken breast\n4 ounces reduced-fat cream cheese, softened\n¾ cup shredded white Cheddar cheese\n1 ½ teaspoons cornstarch\nFresh cilantro, sour cream and/or guacamole for garnish",instructions:"Heat oil in a large pot over medium heat. Add onion and cook, stirring occasionally, until softened, about 3 minutes. Add garlic and cook, stirring, for 1 minute. Add broth, tomatoes, chiles, tortillas, chili powder and cumin. Bring to a boil, stirring occasionally. Reduce heat to a simmer. Cover and cook for 20 minutes. Add chicken and cream cheese, stirring until the cream cheese is melted. Remove from heat. Combine shredded cheese and cornstarch in a small bowl and gradually add to the soup, stirring until melted. Return the pot to medium heat and cook until hot, 1 to 2 minutes. Serve the soup with cilantro, sour cream and/or guacamole, if desired.")
                        
                    
                    ])
                }else if(cat.categoryName == "American"){
                    makeCategoryContent(cat.categoryId,
                    [
                        Recipe(recipeId:giveId(),image:"HealthyBananaBread.png", recipeName:"Healthy Banana Bread", category:cat.categoryId, servingSize:"1 slice", calories:221, protein:4, carb:39,fat:5,ingredients:"1 ¾ cups white whole-wheat flour\n1 ½ teaspoons baking powder\n1 teaspoon ground cinnamon\n½ teaspoon salt\n¼ teaspoon baking soda\n¾ cup sugar\n¼ cup unsalted butter or coconut oil, softened\n2 large eggs\n1 ½ cups mashed ripe bananas (about 3)\n¼ cup buttermilk\n1 teaspoon vanilla extract\n½ cup chopped walnuts or chocolate chips (Optional)",instructions:"Preheat oven to 350 degrees F. Coat a 9-by-5-inch loaf pan with cooking spray. Whisk flour, baking powder, cinnamon, salt and baking soda in a medium bowl. Beat sugar and butter (or coconut oil) in a bowl with an electric mixer on medium-high until well combined. Add eggs, one at a time, beating well after each adding. Add banana, buttermilk and vanilla; beat until combined. Add flour mixture; beat on low speed until just combined. Fold in walnuts (or chocolate chips), if using. Pour the batter into the prepared pan. Bake until a toothpick inserted in the center comes out clean, 45 to 55 minutes. Let cool in the pan for 10 minutes, then transfer to a wire rack to cool completely."),
                        Recipe(recipeId:giveId(),image:"Pimiento-Cheese-StuffedBisonBurgers.png", recipeName:"Pimiento-Cheese-Stuffed Bison Burgers", category:cat.categoryId, servingSize:"1 burger", calories:468, protein:30, carb:31,fat:26,ingredients:"¼ cup fine cornmeal\n1 ¾ teaspoons smoked paprika, divided\n½ teaspoon salt, divided\n½ teaspoon ground pepper, divided\n1 medium green tomato, cut into four 1/2-inch-thick slices\n1 tablespoon canola oil\n1 pound ground bison\n1 tablespoon Worcestershire sauce\n4 tablespoons pimiento cheese spread\n4 whole-wheat hamburger buns, split\n½ cup light mayonnaise\n1 tablespoon lemon juice\n2 cups torn lettuce leaves",instructions:"Preheat grill to medium-high. Combine cornmeal, 1 teaspoon smoked paprika and 1/4 teaspoon each salt and pepper in a shallow dish. Dredge tomato slices in the cornmeal mixture. Heat oil on a griddle or in a large skillet over medium-high heat. Add the tomato slices and cook, flipping once, until golden, about 5 minutes. Meanwhile, mix bison, Worcestershire and the remaining 1/4 teaspoon each salt and pepper in a medium bowl. Divide the mixture into 8 portions and form each into a patty. Place 1 tablespoon pimiento cheese in the center of 4 patties. Place the remaining 4 patties on top and pinch the edges together to seal. Oil the grill rack by holding an oil-soaked paper towel with tongs. Grill the buns, cut-side down, until toasted, about 2 minutes. Grill the burgers, flipping once, until an instant-read thermometer inserted in the center registers 165°F, about 10 minutes.  Meanwhile, mix mayonnaise, lemon juice and the remaining 3/4 teaspoon smoked paprika in a small bowl. Spread over the cut sides of the buns. Divide lettuce among the bun bottoms. Top with the patties, tomatoes and the bun tops."),
                        Recipe(recipeId:giveId(),image:"Southern-StyleOven-FriedChicken.png", recipeName:"Southern-Style Oven-Fried Chicken", category:cat.categoryId, servingSize:"1 thigh", calories:389, protein:30, carb:20,fat:19,ingredients:"2 cups nonfat buttermilk\n¾ teaspoon salt, divided\n4 bone-in, skinless chicken thighs (about 1 1/2 lbs. total)\n¾ cup panko breadcrumbs\n1 tablespoon cornstarch\n½ teaspoon garlic powder\n½ teaspoon onion powder\n½ teaspoon smoked paprika\n¼ teaspoon cayenne pepper\n¼ teaspoon ground pepper\n3 tablespoons canola oil, divided",instructions:"Combine buttermilk and 1/2 tsp. salt in a large bowl. Add chicken; toss to coat. Cover and refrigerate for at least 2 hours or up to 8 hours. When ready to cook, preheat oven to 475 degrees F. Combine panko, cornstarch, garlic powder, onion powder, paprika, cayenne, and ground pepper in a shallow dish. Remove the chicken from the buttermilk mixture, letting excess drip off, and dredge it in the panko mixture, pressing gently to adhere. Gently shake off excess breading; transfer the chicken to a plate and sprinkle evenly with the remaining 1/4 tsp. salt. Heat 1 1/2 Tbsp. oil in a large cast-iron or oven-safe nonstick skillet over medium-high heat. Add the chicken to the pan, tilting as needed so each piece comes in contact with the oil; cook until browned on the bottom, 3 to 4 minutes. Transfer the chicken, browned-side down, to a wire rack set over a baking sheet. Add the remaining 1 1/2 Tbsp. oil to the pan; cook until heated, about 1 minute. Return the chicken, browned-side up, to the pan, tilting as needed so each piece comes in contact with the oil. Transfer the pan to the oven (or use a baking dish). Bake until an instant-read thermometer inserted in the thickest part registers 165 degrees F, 14 to 16 minutes."),
                        Recipe(recipeId:giveId(),image:"ClassicPotatoSalad.png", recipeName:"Classic Potato Salad", category:cat.categoryId, servingSize:"about 3/4 cup", calories:146, protein:4, carb:24,fat:3,ingredients:"2 ½ pounds yellow or red potatoes, scrubbed and diced (1/2- to 1-inch)\n¾ teaspoon salt, divided\n½ cup mayonnaise\n½ cup low-fat plain yogurt\n¼ cup finely chopped onion\n2 tablespoons Dijon mustard\n½ teaspoon ground pepper\n2 hard-boiled eggs, chopped\n1 cup chopped celery",instructions:"Bring 1 to 2 inches of water to a boil in a large saucepan (or pot) fitted with a steamer basket. Add potatoes, cover and cook until tender, 12 to 15 minutes. Spread in a single layer on a rimmed baking sheet and sprinkle with 1/4 teaspoon salt; let cool 15 minutes. Meanwhile, whisk mayonnaise, yogurt, onion, mustard, pepper and the remaining 1/2 teaspoon salt in a large bowl. Add the potatoes, eggs and celery; stir well to coat. Serve at room temperature or refrigerate until cold."),
                        Recipe(recipeId:giveId(),image:"PhillyCheesesteakStuffedPeppers.png", recipeName:"Philly Cheesesteak Stuffed Peppers", category:cat.categoryId, servingSize:"1/2 stuffed pepper", calories:308, protein:29, carb:11,fat:16,ingredients:"2 large bell peppers, halved lengthwise, seeds removed\n1 tablespoon extra-virgin olive oil\n1 large onion, halved and sliced\n1 (8 ounce) package mushrooms, thinly sliced\n12 ounces top round steak, thinly sliced\n1 tablespoon Italian seasoning\n½ teaspoon ground pepper\n¼ teaspoon salt\n1 tablespoon Worcestershire sauce\n4 slices provolone cheese",instructions:"Preheat oven to 375 degrees F. Place pepper halves on a rimmed baking sheet. Bake until tender but still holding their shape, about 30 minutes. Meanwhile, heat oil in a large skillet over medium heat. Add onion and cook, stirring, until starting to brown, 4 to 5 minutes. Add mushrooms and cook, stirring, until they're softened and release their juices, about 5 minutes more. Add steak, Italian seasoning, pepper and salt; cook, stirring, until the steak is just cooked through, 3 to 5 minutes more. Remove from heat and stir in Worcestershire. Preheat broiler to high. Divide the filling between the pepper halves and top each with a slice of cheese. Broil 5 inches from the heat until the cheese is melted and lightly browned, 2 to 3 minutes.")
                    ]
                    )
                }else if(cat.categoryName == "French"){
                    makeCategoryContent(cat.categoryId,
                    [
                        Recipe(recipeId:giveId(),image:"FrenchRatatouille.png", recipeName:"French Ratatouille", category:cat.categoryId, servingSize:"1 cup", calories:200, protein:3, carb:15,fat:14,ingredients:"4 tablespoons extra-virgin olive oil, divided\n1 small onion, thinly sliced\n1 red bell pepper, thinly sliced\n½ teaspoon salt, divided\n1 large eggplant (about 1 pound), thinly sliced\n2 small zucchini and/or summer squash (about 12 ounces), thinly sliced\n3 medium tomatoes, thinly sliced\n¼ teaspoon ground pepper\n1 tablespoon red-wine vinegar\n1 tablespoon chopped fresh marjoram",instructions:"Preheat oven to 425 degrees F. Heat 1 tablespoon oil in a large cast-iron skillet over medium heat. Add onion, bell pepper and 1/4 teaspoon salt. Cook, stirring frequently, until the pepper is soft and the onion is beginning to brown, about 10 minutes. Remove the pan from the heat. Carefully layer eggplant, zucchini (and/or summer squash) and tomatoes in an alternating shingle pattern over the pepper and onion. (They will overlap quite a bit.) If you have extra vegetable slices, save them for another use. Drizzle with 2 tablespoons oil and sprinkle with pepper and the remaining 1/4 teaspoon salt. Place the pan in the oven and bake until the vegetables are tender, about 1 hour. Drizzle vinegar and the remaining 1 tablespoon oil over the top and sprinkle with marjoram. Let cool for about 5 minutes before serving. Leftovers can be refrigerated for up to 4 days."),
                        Recipe(recipeId:giveId(),image:"Slow-CookerFrenchOnionSoupwithGruyereToasts.png", recipeName:"Slow-Cooker French Onion Soup with Gruyère Toasts", category:cat.categoryId, servingSize:"about 1 1/2 cups soup, 2 toasts", calories:259, protein:11, carb:32,fat:10,ingredients:"Cooking spray\n10 cups vertically sliced onions (from 5 onions)\n2 tablespoons unsalted butter, melted\n½ teaspoon black pepper\n6 cups unsalted beef stock\n¼ cup dry Marsala wine\n1 teaspoon chopped fresh thyme, plus more for garnish\n¾ teaspoon kosher salt\n12 ounces whole-wheat baguette (see Tip), cut into 16 slices\n5 ounces Gruyère cheese, shredded (about 1 1/4 cups)",instructions:"Coat a 4-quart slow cooker with cooking spray. Stir together the onions, butter and pepper in the slow cooker; cover and cook on LOW until the onions are very soft and deep golden brown, about 10 hours. Stir in the stock, marsala, thyme and salt. Cover and cook on HIGH until the flavors are blended, about 2 hours. Preheat the broiler with the oven rack 6 inches from the heat. Place the baguette slices on a baking sheet, and sprinkle evenly with the Gruyère. Broil until the Gruyère melts, 2 to 3 minutes. Ladle the soup into bowls. Top with the cheese toasts. Garnish with the additional thyme, if desired."),
                        Recipe(recipeId:giveId(),image:"QuicheLorraine.png", recipeName:"Quiche Lorraine", category:cat.categoryId, servingSize:"1 wedge", calories:332, protein:15, carb:17,fat:23,ingredients:"1 (9 inch) prepared whole-wheat pie crust\n4 ounces thick-cut bacon (about 2 slices), cut into 1/2-inch pieces\n1 cup thinly sliced onion\n4 large eggs, lightly beaten\n1 ½ cups whole milk\n¼ teaspoon freshly grated nutmeg\n¼ teaspoon salt\n¼ teaspoon ground pepper\n1 cup shredded Gruyère cheese",instructions:"Preheat oven to 375 degrees F. Pierce bottom and sides of pie crust with a fork. Bake for 15 minutes. Transfer to a wire rack. Reduce oven temperature to 350 degrees. Meanwhile, cook bacon in a large skillet over medium-low heat, stirring occasionally, until crisp, 8 to 10 minutes. Remove to a clean plate with a slotted spoon. Add onion to the pan and cook, stirring occasionally, until tender, 4 to 6 minutes. Scrape the onion into the crust. Whisk eggs, milk, nutmeg, salt and pepper in a medium bowl. Sprinkle the bacon and half the Gruyère over the onion, then pour the egg mixture over the top. Sprinkle with the remaining cheese. Set the pan on a baking sheet. Bake the quiche until the top is golden brown and the filling is set, about 40 minutes. Let cool for 15 minutes before serving."),
                        Recipe(recipeId:giveId(),image:"HerbCheddarGougeres.png", recipeName:"Herb & Cheddar Gougères", category:cat.categoryId, servingSize:"about 2", calories:64, protein:2, carb:3,fat:4,ingredients:"¾ cup water\n4 tablespoons unsalted butter\n¼ teaspoon salt\n¾ cup all-purpose flour\n2 large eggs\n1 ½ cups shredded extra-sharp Cheddar cheese\n1 teaspoon Dijon mustard\n1 teaspoon chopped fresh thyme\n½ teaspoon chopped fresh rosemary",instructions:"Position racks in upper and lower thirds of oven; preheat to 400 degrees F. Line 2 large baking sheets with parchment paper. Combine water, butter and salt in a medium saucepan. Bring to a simmer over medium-high heat. Reduce heat to medium-low, add flour and mix vigorously with a wooden spoon to form a smooth dough. Cook, stirring, for 2 minutes. The dough should dry out slightly and pull away from the pan. Scrape the dough into a medium bowl and let cool for 2 minutes. Using a wooden spoon, beat eggs one at a time into the dough, beating thoroughly after each addition. The batter will separate after each egg, but keep stirring: it will come back together. Add cheese, mustard, thyme and rosemary and fold to combine. Transfer the dough to a pastry bag fitted with a round 3/8- to 3/4-inch pastry tip (or use a gallon-size plastic bag with about 3/4 inch snipped off a corner). Pipe 25 small mounds of dough onto each prepared baking sheet, making each a littler wider than a quarter. Bake, rotating the pans front to back and top to bottom halfway through, until puffed and golden, 18 to 20 minutes. Serve warm."),
                        Recipe(recipeId:giveId(),image:"CranberryClafoutis.png", recipeName:"Cranberry Clafoutis", category:cat.categoryId, servingSize:"scant 1/2 cup", calories:176, protein:5, carb:32,fat:3,ingredients:"2 cups whole milk\n¾ cup granulated sugar\n½ cup all-purpose flour\n½ cup whole-wheat pastry flour\n3 large eggs\n2 teaspoons vanilla extract\n1 teaspoon salt\n1 ½ cups fresh cranberries\nConfectioners' sugar (optional)",instructions:"Preheat oven to 450°F. Combine milk, sugar, all-purpose flour, whole-wheat flour, eggs, vanilla and salt in a blender. Blend until very smooth, about 1 minute. Place a 10-inch or similar shallow 1 1/2-quart baking dish in the oven for 5 minutes. Working quickly, remove it from the oven and coat with cooking spray. Immediately add cranberries to the baking dish and pour the batter over them. Bake until the clafoutis is set and puffed, 20 to 25 minutes. Let cool for about 15 minutes (it will deflate as it cools). Dust with confectioners' sugar, if desired, before serving.")
                    ]
                    )
                }else if(cat.categoryName == "Chinese"){
                    makeCategoryContent(cat.categoryId,
                    [
                        Recipe(recipeId:giveId(),image:"ClassicSesameNoodleswithChicken.png", recipeName:"Classic Sesame Noodles with Chicken", category:cat.categoryId, servingSize:"1 3/4 cups", calories:460, protein:28, carb:53,fat:16,ingredients:"8 ounces whole-wheat spaghetti\n3 tablespoons toasted (dark) sesame oil\n2 scallions, chopped\n1 tablespoon minced garlic\n2 teaspoons minced fresh ginger\n1 teaspoon brown sugar\n2 tablespoons reduced-sodium soy sauce\n2 tablespoons ketchup\n8 ounces cooked boneless, skinless chicken breast, shredded\n1 cup julienned carrots\n1 cup sliced snap peas\n3 tablespoons toasted sesame seeds",instructions:"Cook spaghetti in a pot of boiling water according to package directions. Drain, rinse and transfer to a large bowl. Combine sesame oil, scallions, garlic, ginger and brown sugar in a small saucepan. Heat over medium heat until starting to sizzle. Cook for 15 seconds. Remove from heat and stir in soy sauce and ketchup. Add to the noodles along with chicken, carrots, snap peas and sesame seeds; gently toss to combine."),
                        Recipe(recipeId:giveId(),image:"BeefStir-FrywithBabyBokChoyGinger.png", recipeName:"Beef Stir-Fry with Baby Bok Choy & Ginger", category:cat.categoryId, servingSize:"1 1/4 cups", calories:247, protein:25, carb:6,fat:12,ingredients:"12 ounces beef flank steak, trimmed\n1 tablespoon minced fresh ginger\n1 ½ teaspoons reduced-sodium soy sauce\n1 teaspoon dry sherry plus 1 Tbsp., divided\n1 teaspoon cornstarch\n1 teaspoon toasted sesame oil\n2 tablespoons oyster-flavored sauce, preferably Lee Kum Kee Premium\n1 tablespoon vegetable oil\n1 pound baby bok choy, trimmed and cut into 2-inch pieces (about 8 cups)\n3 tablespoons unsalted chicken broth",instructions:"Cut beef with the grain into 2-inch-wide strips. Cut each strip across the grain into 1/4-inch-thick slices. Combine the beef, ginger, soy sauce, 1 tsp. sherry, and cornstarch in a medium bowl; stir until the cornstarch is no longer visible. Add sesame oil and stir until the beef is lightly coated. Combine oyster-flavored sauce and the remaining 1 Tbsp. sherry in a small bowl. Set aside. Heat a 14-inch flat-bottomed carbon-steel wok (or a 12-inch stainless-steel skillet) over high heat until a drop of water vaporizes within 1 to 2 seconds of contact. Swirl in vegetable oil. Add the beef in an even layer; cook, undisturbed, until it begins to brown, about 1 minute. Using a metal spatula, stir-fry until lightly browned but not cooked through, 30 seconds to 1 minute more. Transfer to a plate. Add bok choy and broth to the pan. Cover and cook until the bok choy greens are bright green and almost all the liquid has been absorbed, 1 to 2 minutes. Return the beef to the pan, add the reserved sauce, and stir-fry until the beef is just cooked through and the bok choy is tender-crisp, 30 seconds to 1 minute."),
                        Recipe(recipeId:giveId(),image:"SpicyTofuHotpot.png", recipeName:"Spicy Tofu Hotpot", category:cat.categoryId, servingSize:"1 1/2 cups", calories:214, protein:12, carb:30,fat:5,ingredients:"6 cloves garlic, minced\n2 teaspoons canola oil\n1 tablespoon brown sugar\n14 ounces firm tofu, preferably water-packed\n¼ cup reduced-sodium soy sauce\n2 teaspoons chile-garlic sauce, or to taste\n4 cups thinly sliced tender bok choy greens\n8 ounces fresh Chinese-style (lo mein) noodles\n½ cup chopped fresh cilantro\n4 cups vegetable broth, or reduced-sodium chicken broth\n4 ounces fresh shiitake mushrooms, stemmed and sliced (about 2 cups)\n2 tablespoons grated fresh ginger",instructions:"Drain and rinse tofu; pat dry. Cut the block into 1-inch cubes. Heat oil in a Dutch oven over medium heat. Add ginger and garlic; cook, stirring, until fragrant, about 1 minute. Add mushrooms and cook until slightly soft, 2 to 3 minutes. Stir in sugar, broth, soy sauce and chile-garlic sauce; cover and bring to a boil. Add bok choy and tofu, cover and simmer until greens are wilted, about 2 minutes. Raise heat to high and add the noodles, pushing them down into the broth. Cook, covered, until the noodles are tender, 2 to 3 minutes. Remove from the heat and stir in cilantro."),
                        Recipe(recipeId:giveId(),image:"ScallopShrimpDumplings.png", recipeName:"Scallop & Shrimp Dumplings", category:cat.categoryId, servingSize:"1 dumpling & 1 teaspoon sauce", calories:41, protein:2, carb:5,fat:1,ingredients:"8 ounces scallops, minced\n4 ounces raw shrimp, peeled, deveined and minced\n½ cup minced scallions\n1 tablespoon minced fresh ginger\n3 cloves garlic, minced\n2 tablespoons reduced-sodium soy sauce\n2 teaspoons toasted sesame oil\n¼ teaspoon freshly ground pepper\n36 round (gyoza) dumpling wrappers, (see Kitchen Tip)\n2 tablespoons canola oil, divided\n¾ cup water, divided\nGinger-Garlic Dipping Sauce, (recipe follows), optional",instructions:"Combine scallops, shrimp, scallions, ginger, garlic, soy sauce, sesame oil and pepper in a large bowl. Organize your work area with a bowl of cold water, your stack of dumpling wrappers and a floured baking sheet to hold filled dumplings. Working with one dumpling wrapper at a time, dip your finger into the water and moisten the edges of the circle. Spoon about 1 1/2 teaspoons of filling into the center. Fold the wrapper over to form a half circle. Pinch the edges together to seal. Repeat with remaining wrappers and filling. Cover the wrappers and finished dumplings with moist paper towels to prevent drying. Preheat oven to 200 degrees F. Mix 1 tablespoon canola oil with 1/4 cup water in a large nonstick skillet and place over medium heat; bring to a simmer. Carefully arrange one-third of the dumplings in the skillet so they are not touching; cover and cook until the dumplings puff up and are light brown on the bottom, 4 to 5 minutes. Carefully flip the dumplings with tongs and cook for 1 minute more. Transfer the dumplings to a baking sheet and keep warm in the oven. Repeat the procedure with another 1/4 cup water, the remaining 1 tablespoon canola oil and half the remaining dumplings. Cook the final batch of dumplings in the remaining 1/4 cup water, adjusting the heat as necessary to prevent scorching. (There will be enough oil left in the pan for the final batch.) Serve hot with Ginger-Garlic Dipping Sauce, if desired."),
                        Recipe(recipeId:giveId(),image:"GeneralTsosChicken.png", recipeName:"General Tso's Chicken", category:cat.categoryId, servingSize:"about 1 1/2 cups", calories:364, protein:24, carb:20,fat:19,ingredients:"5 tablespoons cornstarch, divided\n2 tablespoons reduced-sodium soy sauce, divided\n2 tablespoons Chinese rice wine or dry sherry, divided\n1 large egg white\n1 pound boneless, skinless chicken thighs, cut into 1-inch pieces\n¾ cup water\n2 tablespoons hoisin sauce\n1 tablespoon rice vinegar\n3 tablespoons canola oil, divided\n2 scallions, sliced\n2 cloves garlic, minced\n4 cups snow peas",instructions:"Combine 4 tablespoons cornstarch, 1 tablespoon each soy sauce and rice wine (or sherry) and egg white in a bowl. Add chicken and stir to coat. Combine the remaining 1 tablespoon each cornstarch, soy sauce and rice wine (or sherry), water, hoisin and rice vinegar in a small bowl. Set aside. Heat 2 tablespoons oil in a wok or large cast-iron skillet over high heat. Add the chicken; cook without turning, breaking up stuck-together pieces, until golden on the bottom, 2 minutes. Stir; continue cooking until golden on all sides, 1 to 2 minutes more. Transfer to a plate. Add the remaining 1 tablespoon oil, scallions and garlic. Cook, stirring, until fragrant, about 15 seconds. Add peas; cook, stirring often, until bright green, 2 to 3 minutes. Add the reserved sauce mixture; cook, stirring, until thick, about 1 minute. Return the chicken to the pan; cook, stirring, until heated through, about 1 minute more.")
                    ]
                    )
                }
                
            
                
                let encodedCategoryData = try? propertyListEncoder.encode(categoryArr)
                try? encodedCategoryData?.write(to: archiveURL, options: .noFileProtection)
                
                archiveURL = documentsDirectory.appendingPathComponent("users").appendingPathExtension("plist")
                
                let userArr: [User] = [];
                
                let encodedUserData = try? propertyListEncoder.encode(userArr)
                try? encodedUserData?.write(to: archiveURL, options: .noFileProtection)
            
            }
            
        }
        
        /*
        var arr: [Category] = [Category(categoryId: giveId(), categoryName: "Mexican"),Category(categoryId: giveId(), categoryName: "American"),Category(categoryId: giveId(), categoryName: "Indian"),Category(categoryId: giveId(), categoryName: "Egyptian")]
        let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        let archiveURL = documentsDirectory.appendingPathComponent("categories").appendingPathExtension("plist")
        let propertyListEncoder = PropertyListEncoder()
        let encodedData = try? propertyListEncoder.encode(arr)
        try? encodedData?.write(to: archiveURL, options: .noFileProtection)
       */
        /*var arr: [User] = [User(userId: giveId(), userName: "admin", userPassword: "admin", userBio: "Admin", userImage: "user.png"),User(userId: giveId(), userName: "hamood", userPassword: "123", userBio: "hamood #EZ", userImage: "user.png")];
        let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        let archiveURL = documentsDirectory.appendingPathComponent("users").appendingPathExtension("plist")
        let propertyListEncoder = PropertyListEncoder()
        let encodedData = try? propertyListEncoder.encode(arr)
        try? encodedData?.write(to: archiveURL, options: .noFileProtection)
        */
        return true
    }
    
    func signedUp()->Bool{
            let defaults = UserDefaults.standard
            
            if defaults.bool(forKey: "signedUp"){
                return true
            }else{
                return false
            }
        }
    // MARK: UISceneSession Lifecycle

    func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration {
        // Called when a new scene session is being created.
        // Use this method to select a configuration to create the new scene with.
        return UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
    }

    func application(_ application: UIApplication, didDiscardSceneSessions sceneSessions: Set<UISceneSession>) {
        // Called when the user discards a scene session.
        // If any sessions were discarded while the application was not running, this will be called shortly after application:didFinishLaunchingWithOptions.
        // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
    }
    


}

